# This workflow publishes the npm package to the npm registry.

name: Publish to npm

on:
    workflow_dispatch:
    push:
        tags:
            # This specifies that the workflow runs only when a new Git tag is pushed.
            # The tag must match the format 'vX.Y.Z' (e.g., v1.0.0).
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        name: Build, Lint, Test, and Publish
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Set up Node.js for building the project
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"
                  registry-url: "https://registry.npmjs.org" # Sets the registry URL.

            # Install dependencies
            - name: Install Node dependencies
              run: npm install

            # Install and activate Emscripten SDK (if required for wasm build)
            - name: Install and Activate Emscripten SDK
              run: |
                  git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
                  ~/emsdk/emsdk install latest
                  ~/emsdk/emsdk activate latest
                  source ~/emsdk/emsdk_env.sh
                  python build --env prod
              shell: bash

            # Run lint
            - name: Run lint
              run: npm run lint

            # Run Build
            - name: Run Build
              run: npm run build

            # Publishes the package to the npm registry.
            # The --access public flag is required for scoped packages to be public.
            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Uses the secret for authentication.
