name: Deploy to GitHub Pages

# This workflow is triggered on a push to a tag starting with 'v' or a manual trigger.
on:
    workflow_dispatch:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    deploy:
        name: Build and Deploy Example
        runs-on: ubuntu-latest

        # Set permissions for the GITHUB_TOKEN to allow Pages deployment.
        permissions:
            pages: write # Required to deploy to GitHub Pages
            id-token: write # Required to use OpenID Connect for authentication

        steps:
            # Checkout the repository with all its history and submodules.
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  submodules: "true" # This ensures your swisseph submodule is also cloned.

            # Set up Node.js for building the project.
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"

            # Install dependencies from package.json.
            - name: Install Node dependencies
              run: npm install

            # Install and activate Emscripten SDK and build the wasm module.
            # The shell: bash is important here to source the emsdk environment variables.
            - name: Install and Activate Emscripten SDK
              run: |
                  git submodule init
                  git submodule update --recursive --depth 1
                  git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
                  ~/emsdk/emsdk install latest
                  ~/emsdk/emsdk activate latest
                  source ~/emsdk/emsdk_env.sh
                  npm run build:wasm
              shell: bash

            # Run linting checks.
            - name: Run lint
              run: npm run lint

            # Run the main build command.
            - name: Run Build
              run: npm run build

            # Move the 'dist' folder into the 'example' folder.
            - name: Move dist into example
              run: mv dist example/dist

            # Prepare the deployable artifact for GitHub Pages.
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            # Upload the 'example' folder as a Pages artifact.
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # The directory to upload.
                  path: "./example"

            # Deploy the artifact to GitHub Pages.
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
